<a href="https://colab.research.google.com/github/vikashkumar97983282-glitch/machine-learning/blob/main/K_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**KNN (K-NearestNeighbors)**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/ml_practical/salary.csv')

In [ ]:
data

,age,education.num,capital.gain,hours.per.week,income
0,90,9,0,40,<=50K
1,82,9,0,18,<=50K
2,66,10,0,40,<=50K
3,54,4,0,40,<=50K
4,41,10,0,40,<=50K
...,...,...,...,...,...
32556,22,10,0,40,<=50K
32557,27,12,0,38,<=50K
32558,40,9,0,40,>50K
32559,58,9,0,40,<=50K


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   education.num   32561 non-null  int64 
 2   capital.gain    32561 non-null  int64 
 3   hours.per.week  32561 non-null  int64 
 4   income          32561 non-null  object
dtypes: int64(4), object(1)
memory usage: 1.2+ MB


In [ ]:
data.shape

(32561, 5)

In [ ]:
data.isnull().sum()

,0
age,0
education.num,0
capital.gain,0
hours.per.week,0
income,0


In [ ]:
data.sample(5)

,age,education.num,capital.gain,hours.per.week,income
9021,43,13,0,39,<=50K
20014,31,9,0,50,<=50K
5434,45,10,0,45,<=50K
12018,57,9,0,72,<=50K
32042,53,16,0,50,>50K


In [ ]:
from sklearn.model_selection import train_test_split

X = data.drop('income', axis=1)
y = data['income']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
# label encoding
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

y = data['income']
data['income']=label.fit_transform(y)
label.classes_

array(['<=50K', '>50K'], dtype=object)

In [ ]:
data

,age,education.num,capital.gain,hours.per.week,income
0,90,9,0,40,0
1,82,9,0,18,0
2,66,10,0,40,0
3,54,4,0,40,0
4,41,10,0,40,0
...,...,...,...,...,...
32556,22,10,0,40,0
32557,27,12,0,38,0
32558,40,9,0,40,1
32559,58,9,0,40,0


In [ ]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1]

In [ ]:
y

,income
0,0
1,0
2,0
3,0
4,0
...,...
32556,0
32557,0
32558,1
32559,0


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(26048, 4)

In [ ]:
print("min: ",x.min())
print("max ",x.max())

min:  0
max  99999


In [ ]:
print(data['age'].min())
print(data['age'].max())
print(data['education.num'].min())
print(data['education.num'].max())


17
90
1
16


In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [ ]:
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [ ]:
X_train_scaled

array([[-0.92195464, -0.42172678, -0.14716638, -1.25838714],
       [-1.06915047, -0.42172678, -0.14716638, -0.44751661],
       [-0.18597545,  1.12825935, -0.14716638, -0.04208134],
       ...,
       [ 1.212385  , -0.42172678, -0.14716638, -0.04208134],
       [ 0.18201414, -0.03423025, -0.14716638,  0.76878919],
       [-1.21634631, -0.42172678, -0.14716638,  0.76878919]])

In [ ]:
#metric='minkowski', p=2

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=50)

In [ ]:
y_pred = knn.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_pred,y_test)*100

82.11269768155995

In [ ]:
cm = confusion_matrix(y_pred,y_test)
cm

array([[4746,  935],
       [ 230,  602]])

In [ ]:
Age=int(input("Enter age: "))
Education=int(input("Enter education: "))
Captital_Gain=int(input("Enter capital gain: "))
working_hous= int(input("Enter working hours: "))
newEmp=[[Age, Education, Captital_Gain,working_hous]]
result= knn.predict(newEmp)
print(result)


Enter age: 11
Enter education: 78
Enter capital gain: 0
Enter working hours: 90
[1]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred)*100)

[[4746  230]
 [ 935  602]]
82.11269768155995
